# Internal applications configuration (from src/ directory)
argocd:
  app1:
    enabled: true
  app2:
    enabled: true
  externalApps:
    phpWebApp:
      enabled: false

# Target repository for internal applications
targetRepo: git@github.com:triplom/infrastructure-repo-argocd.git
targetRevision: HEAD

# External repositories configuration
externalApps:
  phpWebApp:
    targetRevision: HEAD