apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app2
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        cluster: https://kubernetes.default.svc
      - env: qa
        cluster: https://kubernetes.default.svc
      - env: prod
        cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'app2-{{env}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: applications
      source:
        repoURL: https://github.com/triplom/infrastructure-repo-argocd.git
        targetRevision: HEAD
        path: apps/app2/overlays/{{env}}
      destination:
        server: '{{cluster}}'
        namespace: app2-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
