apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- datasources-config.yaml
- dashboards-config.yaml
- dashboard-kubernetes.yaml
- dashboard-k8s-comprehensive.yaml
- argocd-dashboard-configmap.yaml
- thesis-chapter6-dashboard.yaml