apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

namespace: app1-dev

# Environment-specific patches
patches:
- path: patches.yaml
  target:
    kind: Deployment
    name: app1