# Monitoring components configuration
argocd:
  prometheus:
    enabled: true
    ingress: "https://prometheus-mycompany.com"
  grafana:
    enabled: true
    ingress: "https://grafana-mycompany.com"

# Target repository for monitoring components
targetRepo: https://github.com/triplom/infrastructure-repo-argocd.git
targetRevision: HEAD