# File: apps/app2/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
patchesStrategicMerge:
- patches.yaml
namespace: app2-dev