# File: infrastructure/argocd/applications/root.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/triplom/infrastructure-repo-argocd.git
    targetRevision: HEAD
    path: infrastructure/argocd/applications
    directory:
      recurse: true
      exclude: |
        root.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true