apiVersion: v1
kind: Secret
metadata:
  name: argocd-server-tls
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: localhost
  dnsNames:
  - localhost
  - argocd.local
  - argocd-server
  - argocd-server.argocd
  - argocd-server.argocd.svc
  - argocd-server.argocd.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
  - ::1
  usages:
  - digital signature
  - key encipherment
  - server auth