apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- nginx-patch.yaml
- php-patch.yaml
images:
- name: php-web-app
  newName: ghcr.io/triplom/php-web-app
  newTag: main
