apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- nodeport-service.yaml
- configmap.yaml
- rbac.yaml
- rules-configmap.yaml
- thesis-chapter6-metrics.yaml