
{{ if .Values.argocd.app1.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: dev
        cluster: https://kubernetes.default.svc
      - env: qa
        cluster: https://kubernetes.default.svc
      - env: prod
        cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: 'app1-{{env}}'
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: applications
      source:
        repoURL: {{ .Values.targetRepo }}
        targetRevision: {{ .Values.targetRevision }}
        path: apps/app1/overlays/{{env}}
      destination:
        server: '{{cluster}}'
        namespace: 'app1-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
{{ end }}