{{- if .Values.headlamp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://headlamp-k8s.github.io/headlamp
    chart: headlamp
    targetRevision: {{ .Values.headlamp.chartVersion }}
    helm:
      releaseName: headlamp
      values: |
        replicaCount: 1
        service:
          type: NodePort
          nodePort: 30900
        config:
          pluginsDir: /headlamp/plugins
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
