apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-app2
  template:
    metadata:
      labels:
        app: external-app2
    spec:
      containers:
      - name: external-app2
        image: ghcr.io/triplom/external-app2:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
