{{ if .Values.argocd.ingressRules.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-rules
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: {{ .Values.targetRepo }}
    targetRevision: {{ .Values.targetRevision }}
    path: infrastructure/ingress-rules
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
{{ end }}
